### ISSUE TITLE
Recovered data not populating

### ISSUE THREAD

**Issue by jakecomp** [jakecomp/covid19-dashboard#1]
## BUG: ValueError with recovered data ## 
When brining up the server and performing our data analysis I get the following error: 

```
Internal Server Error: /trends
Traceback (most recent call last):
  File "/home/jakob/Desktop/covid19-dashboard/covid_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/jakob/Desktop/covid19-dashboard/covid_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jakob/Desktop/covid19-dashboard/covid_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jakob/Desktop/covid19-dashboard/processdata/views.py", line 37, in trends
    'recovered_trend': int(round(df.Recovered)),
ValueError: cannot convert float NaN to integer
``` 
When going to the URL we can see that the recovered data appears to be 0 as shown by the image below: 
![image](https://user-images.githubusercontent.com/44540913/160300384-28ee4838-4364-4341-ab7e-e6654b478de9.png)

### Task ### 
Resolve the ValueError within our recovered data set by eliminating NaN values

**Comment by jakecomp** [comment]
What appears to have happened is in the John Hopkins COVD-19 data set the `Recovered` column seems to have stopped being updated and the entire column appears to be NULL. To get around this im proposing that we calculate the number of people recovered my subtracting the number of confirmed cases by the number of deaths. This is not a perfect substitution however I believe it is an acceptable solution

**Comment by jakecomp** [comment]
Upon further review, seeing as the recovered metric is viewed as unreliable, it will probably be better just to record total vaccinations instead of recovered

**Comment by jakecomp** [comment]
Completed fixes which includes reporting vaccination metrics instead of recovered metrics 
![image](https://user-images.githubusercontent.com/44540913/163728012-41ec1e89-e81f-47be-9f34-85f97f00480c.png)

**Comment by jakecomp** [comment]
![image](https://user-images.githubusercontent.com/44540913/163728027-78d0068d-1e9d-4108-a3ca-e5a168a4d3b0.png)
Note: Green trend line shows daily vaccinations
